### ISSUE TITLE
Impossible kill method generated

### ISSUE THREAD

**Issue by RDIL** [BRYN4444/HitmanRoulette#1]
Hey, so this is a bit specific, but still seems patch-worthy.  

Today I got Erich Soders, with the method being `Reveal Yourself as 47`, and the disguise being `Baseball Player`.

Since this does need to be done in a suit, this is quite literally impossible, so if it could be specifically checked against that would be nice.

Thanks!

**Comment by BRYN4444** [comment]
Thanks for letting me know, and thanks for checking this tool out! There are a few other roulettes out there, and I never really promoted this one, so it's cool to see this bug report in a way.

As for the bug, I'll get to it once I have some free time here soon. Soders' code is unique and tricky.

**Comment by BRYN4444** [comment]
A crude but effective fix. Just had to add a few hoppers for Soders' unique kill options.

The `Reveal Yourself as 47` elimination method will now only appear if the `Specific Disguises` kill requirement is `[OFF]`. Additionally, since these were also part of his options, `Pistol`, `Large Firearm`, and `Explosion` elimination methods will now only appear if the `Specific Firearms` kill requirement is `[ON]`.

Lastly, and this isn't part of the bug, I added a `Save Roulette` option that I've been sitting on for a bit. Just a simple way to copy or save the generated Roulette in .txt form. Thanks for the bug report and thanks again for enjoying the Roulette!

**Comment by RDIL** [comment]
Thanks for the fix!  To be honest, all I think it needs now is more extra objectives.  Nice work :)
